/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// engineeringPlaybookSidebar: [{ type: 'autogenerated', dirName: '.' }]
	engineeringPlaybookSidebar: [
		{
			type: "category",
			label: "Engineering Playbook",
			collapsible: true,
			collapsed: true,
			items: [
				"engineering-playbook/engineering-playbook-checklist",
				{
					type: "category",
					label: "Source Control",
					items: [
						"engineering-playbook/source-control/tech-stack",
						"engineering-playbook/source-control/issues-to-keep-track-on",
						"engineering-playbook/source-control/repository-settings",
						"engineering-playbook/source-control/changelog",
						"engineering-playbook/source-control/labels",
						"engineering-playbook/source-control/pull-request-template",
						"engineering-playbook/source-control/feature-issue-template",
						"engineering-playbook/source-control/docs-issue-template",
						"engineering-playbook/source-control/bug-issue-template",
						"engineering-playbook/source-control/managing-dependencies",
						"engineering-playbook/source-control/dependabot",
					],
				},
				{
					type: "category",
					label: "Agile",
					items: [
						"engineering-playbook/agile/basics",
						"engineering-playbook/agile/agile-roles",
						"engineering-playbook/agile/agile-ceremonies-basics",
						"engineering-playbook/agile/agile-backlog-management",
						"engineering-playbook/agile/the-sprint",
						"engineering-playbook/agile/retrospectives",
						"engineering-playbook/agile/definition-of-ready",
						"engineering-playbook/agile/definition-of-done",
					],
				},
				{
					type: "category",
					label: "Processes",
					items: [
						"engineering-playbook/processes/goals",
						"engineering-playbook/processes/lead",
            "engineering-playbook/processes/tech-interview",
            "engineering-playbook/processes/onboarding",
						"engineering-playbook/processes/critical-chain",
						"engineering-playbook/processes/delayIn-managerial-decision-making",
						"engineering-playbook/processes/productivity-desctruction-meetings",
					],
				},
				{
					type: "category",
					label: "Code Review",
					items: [
						"engineering-playbook/code-review/code-review",
						"engineering-playbook/code-review/code-review-formalization",
					],
				},
				{
					type: "category",
					label: "Design Review",
					items: [
						"engineering-playbook/design-review/design-review",
						"engineering-playbook/design-review/decision-log",
						"engineering-playbook/design-review/design-decision-log",
						"engineering-playbook/design-review/architecture-decision-record",
					],
				},
				{
					type: "category",
					label: "Testing",
					items: [
						"engineering-playbook/testing/quality-strategy",
						"engineering-playbook/testing/zero-bugs-policy",
						"engineering-playbook/testing/quality-metrics",
						"engineering-playbook/testing/why-automated-testing",
						"engineering-playbook/testing/ideal-testing-trophy",
						"engineering-playbook/testing/test-desiderata",
						"engineering-playbook/testing/tdd",
						"engineering-playbook/testing/testing-conventions",
						"engineering-playbook/testing/impact-analyses",
						"engineering-playbook/testing/recommened-linters",
						"engineering-playbook/testing/adding-eslint-to-an-existing-project",
						"engineering-playbook/testing/eslint-over-conventions",
					],
				},
				{
					type: "category",
					label: "CI/CD",
					items: [
						"engineering-playbook/CI-CD/continuous-integration",
						"engineering-playbook/CI-CD/feature-flags",
						"engineering-playbook/CI-CD/feature-flags-release-toggles",
						"engineering-playbook/CI-CD/production-hot-fixes",
						"engineering-playbook/CI-CD/release-log",
						"engineering-playbook/CI-CD/cd-github-vs-gitlab",
						"engineering-playbook/CI-CD/copy-paste-analyzing",
            "engineering-playbook/CI-CD/unused-code-detection",
					],
				},
				{
					type: "category",
					label: "Documentation",
					items: [
						"engineering-playbook/documentation/documentation-first-approach",
						"engineering-playbook/documentation/documentation-store",
					],
				},
				{
					type: "category",
					label: "GraphQL",
					items: ["engineering-playbook/graphql/graphql-disadvantages"],
				},
				{
					type: "category",
					label: "State Management",
					items: [
						"engineering-playbook/state-management/redux-hidden-dependencies",
					],
				},
				{
					type: "category",
					label: "Developer Experience",
					items: [
						"engineering-playbook/developer-experience/engineer-hardware-software-setup",
						"engineering-playbook/developer-experience/recommended-soft",
					],
				},
				{
					type: "category",
					label: "Growth",
					items: [
						"engineering-playbook/growth/engineer-levels",
						"engineering-playbook/growth/company-engineering-culture",
						"engineering-playbook/growth/engineer-salary-review",
					],
				},
				{
					type: "category",
					label: "UI Design",
					items: ["engineering-playbook/ui-design/ui-design-review"],
				},
			],
		},
		{
			type: "category",
			label: "CLI",
			collapsible: true,
			collapsed: true,
			items: [
				{
					type: "category",
					label: "Changelog Manager",
					items: [
						"cli/changelog-manager/usage",
						"cli/changelog-manager/tech-insights",
					],
				},
			],
		},
	],
};

export default sidebars;
